### ISSUE TITLE
Get error in getting result of purchaseDetail method.

### ISSUE THREAD

**Issue by arefhosseini** [javad-zobeidi/cafebazaar_flutter#1]
for checking purchase of user I use `purchaseDetail(...)` as code below:

MainMethod:
```dart
Future<Map<String, dynamic>> result = BazaarUtils.purchaseDetail("sample2");
      result
          .then((result) {
            if (result == null) {
              print("Purchase is null");
            }
            else {
              print("Already Purched");
            }
          })
          .catchError((error) => print('Detail error: $error'))
          .whenComplete(() {
            widget.onPushLoadingWidget(false);
          });
```

BazaarUtils.purchaseDetail:
```dart
static Future<Map<String, dynamic>> purchaseDetail(String sku) async {
    Map<String, dynamic> result = await CafebazaarFlutter.getPurchase(sku: sku);
    return result;
}
```

But in logs I got these error:
```dart
Detail error: NoSuchMethodError: The getter 'length' was called on null.
    Receiver: null
    Tried calling: length
```

I already use `initPay(...)` for initializing payment.
How can I check that user purchased some product? 
Thanks.

**Comment by Seven7up** [comment]
hello
this method fixed in next version soon

you can use this

Map<String,dynamic> result = CafebazaarFlutter.getPurchase(sku:"your product sku") 

the result

'{
    "isSuccess": "true",
    "response":"0",
    "message":"Success (response: 0:OK)",
    "purchase":{
       "orderId":"12999763169054705758.1371079406387615",
       "packageName":"com.example.app",
       "productId":"exampleSku",
       "purchaseTime":1345678900000,
       "purchaseState":0,
       "developerPayload":"bGoa+V7g/yqDXvKRqq+JTFn4uQZbPiQJo4pf9RzJ",
       "purchaseToken":"rojeslcdyyiapnqcynkjyyjh"
     }
}'
