### ISSUE TITLE
خطای کافه بازار به دسترسی PAY_THROUGH_BAZAAR

### ISSUE THREAD

**Issue by reza-najafi1998** [javad-zobeidi/cafebazaar_flutter#12]
سلام من از این کتابخانه فقط جهت انتقال کاربر به صفحه ثبت نظر استفاده کردم اما بعد از انتشار برنامه،توسط بازار رد شد و گفته شده تو فایل مانیفست مجوز  com.farsitel.bazaar.permission.PAY_THROUGH_BAZAAR درخواست شده که برای پرداخت درون برنامه است.
من این مجوز رو اضافه نکردم و الان هم تو فایل مانیفیستم نیست.

**Comment by 2jim** [comment]
توی پوشه projectName\android\app\src\main
فایل AndroidManifest.xml رو باز کن و کد زیر رو اضاف کن
ابتدای فایل هم اسکیماش رو اضاف کن

```
<application>...</application>
 <uses-permission
        android:name="com.farsitel.bazaar.permission.PAY_THROUGH_BAZAAR"
        tools:node="remove" />
```

```
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
```
