### ISSUE TITLE
Could not find com.phelat:poolakey:1.0.0-alpha07

### ISSUE THREAD

**Issue by 2jim** [javad-zobeidi/cafebazaar_flutter#13]
when I call "flutter run" my project throw this error:

[  +83 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[   +1 ms] Execution failed for task ':cafebazaar_flutter:compileDebugAidl'.
[   +1 ms] > Could not resolve all files for configuration ':cafebazaar_flutter:debugCompileClasspath'.
[   +1 ms]    > Could not find com.phelat:poolakey:1.0.0-alpha07.
[        ]      Required by:
[        ]          project :cafebazaar_flutter

**Comment by erfanh3h** [comment]
منم این مشکل رو دارم کسی راه حلی نداره؟

**Comment by javad-zobeidi** [comment]
به نسخه جدید ارتقا بدید
